network:
  host: chat.freenode.net
  port: 6667
  ssl: false
  channels:
    - "#gossip-bot-test"
nick: gossip
ownerNick: gossip_owner
logging:
  level: debug
  splunk:
    enabled: true
    host: splunk.autok8s.raidancampbell.com
    hecPort: 8088
    token: ef1dafce-8d3e-40b1-9a64-82cbc5e4274b
